<?php require('template/header.phtml') ?>


    <div class="row text-center">
    <div class="col-sm-12">
        <h1>Friend Requests</h1>
    </div>
    </div>

<div id="live_request"></div>

<script src="JS/searcher.js"></script>

<?php
//foreach ($view->allRequests as $user) {
//    echo '
//                    <div class="col-sm-4 col-lg-3 p-3">
//                      <div class="card">
//                        <div class="card-body text-center">
//
//                            <p class="card-text">' . $user->getFirstName() . '</p>
//                            <p class="card-text">' . 'Username: ' . $user->getUsername() . '</p>
//                            <p class="card-text">' . $user->getEmail() . '</p>
//                            <p class="card-text"><img src="'. $user->getProfilePicture() . '" </p>
//                            <a href="request.php?accept_user_id='. $user->getUserID().'">Accept</a>
//                            <a href="request.php?reject_user_id='. $user->getUserID().'">Reject</a>
//                        </div>
//                      </div>
//                    </div>';
//
//}
//?>
<!---->
<!---->
<!---->
<!---->
<!---->





<?php require ('template/footer.phtml') ?>
