<?php require('template/header.phtml') ?>

    <div class="row text-center">
        <div class="col-sm-12">
            <h1>Users</h1>
        </div>
    </div>

    <div class="row">
        <?php
        // Display the details of all users
        if (!isset($_SESSION['userID'])) {//when the user is not logged in


            foreach ($view->userDataset as $user) {
                echo '
                    <div class="col-sm-4 col-lg-3 p-3">
                      <div class="card">
                        <div class="card-body text-center">
                     
                            <p class="card-text">' . $user->getUsername() . '</p>
                            <p class="card-text"><img src="'. $user->getProfilePicture() . '" </p>
                        </div>
                      </div>
                    </div>';
            }
        }else{
            //when the user is logged in
            foreach ($view->userDataset as $user) {
                echo '
                    <div class="col-sm-4 col-lg-3 p-3">
                      <div class="card">
                        <div class="card-body text-center">

                            <p class="card-text">' . $user->getFirstName() . '</p>
                            <p class="card-text">' . 'Username: ' . $user->getUsername() . '</p>
                            <p class="card-text">' . $user->getEmail() . '</p>
                            <p class="card-text"><img src="'. $user->getProfilePicture() . '" </p>
                            <a href="./request.php?user_id='. $user->getUserID().'">Request</a>
                            
                        </div>
                      </div>
                    </div>';
            }
        }
        ?>
    </div>






<?php require ('template/footer.phtml') ?>